// Feature 004: produce the block that the renderer pastes into a target pane — a handoff summary
// of another (source) session, generated by the CLI itself via ClaudeCli.summarizeSession.
// This module never touches a PTY; it only turns a sessionId into text. One AbortController per
// importId so the renderer can cancel.
import { existsSync } from 'node:fs'
import type { ClaudeCliLike } from '../claude/claude-cli'
import type { ImportContextPrefs, Project, Session } from '@shared/types'
import { buildHandoffPrompt } from './handoff-prompt'
import { buildImportBlock, DEFAULT_MAX_CHARS, trimSummary } from './import-block'

export interface ContextImporterDeps {
  cli: () => ClaudeCliLike
  getSession: (sessionId: string) => Session | undefined
  getProject: (projectId: string) => Project | undefined
  prefs: () => ImportContextPrefs
  maxChars?: number
  now?: () => number
  fileExists?: (p: string) => boolean
}

export interface SummarizeRequest {
  importId: string
  sourceSessionId: string
}
export interface SummarizeResponse {
  text: string
  truncated: boolean
  model: string
  durationMs: number
}

export class ImportCancelledError extends Error {
  constructor() {
    super('cancelled')
    this.name = 'ImportCancelledError'
  }
}

export class ContextImporter {
  private readonly inflight = new Map<string, AbortController>()
  private readonly now: () => number
  private readonly fileExists: (p: string) => boolean

  constructor(private readonly deps: ContextImporterDeps) {
    this.now = deps.now ?? Date.now
    this.fileExists = deps.fileExists ?? existsSync
  }

  async summarize(req: SummarizeRequest): Promise<SummarizeResponse> {
    if (this.inflight.has(req.importId)) throw new Error('Ya hay una importación con ese id')
    const source = this.deps.getSession(req.sourceSessionId)
    if (!source) throw new Error('La sesión origen ya no existe')
    if (!this.fileExists(source.cwd))
      throw new Error(`La carpeta de la sesión origen ya no existe: ${source.cwd}`)
    const model = this.deps.prefs().model
    const ctrl = new AbortController()
    this.inflight.set(req.importId, ctrl)
    const t0 = this.now()
    try {
      const r = await this.deps.cli().summarizeSession({
        sessionId: source.sessionId,
        cwd: source.cwd,
        model,
        prompt: buildHandoffPrompt(),
        signal: ctrl.signal
      })
      const trimmed = trimSummary(r.text, this.deps.maxChars ?? DEFAULT_MAX_CHARS)
      const project = source.projectId ? this.deps.getProject(source.projectId) : undefined
      const text = buildImportBlock({
        sourceName: source.name,
        projectName: project?.name ?? null,
        text: trimmed.text,
        truncated: trimmed.truncated
      })
      return { text, truncated: trimmed.truncated, model, durationMs: this.now() - t0 }
    } catch (e) {
      if (ctrl.signal.aborted || (e as Error)?.name === 'AbortError')
        throw new ImportCancelledError()
      throw e
    } finally {
      this.inflight.delete(req.importId)
    }
  }

  /** Idempotent: unknown ids are ignored. */
  cancel(importId: string): void {
    this.inflight.get(importId)?.abort()
  }

  get inflightCount(): number {
    return this.inflight.size
  }

  dispose(): void {
    for (const c of this.inflight.values()) c.abort()
    this.inflight.clear()
  }
}
